import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "../../components/ui/header";
import "../globals.css";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function enLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div id="body-container">
                    <Header />
                    <div id="main-contents" className="flex flex-row">
                        <main className="w-screen px-6 mt-6 flex-grow">
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </html>
    );
}
